<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nationality;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        $nationalities = [
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'United States', 'code' => 'US'],
            ['name' => 'United Kingdom', 'code' => 'GB'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Germany', 'code' => 'DE'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Spain', 'code' => 'ES'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'South Korea', 'code' => 'KR'],
            ['name' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Russia', 'code' => 'RU'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Austria', 'code' => 'AT'],
            ['name' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Turkey', 'code' => 'TR'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Tanzania', 'code' => 'TZ'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Algeria', 'code' => 'DZ'],
            ['name' => 'Tunisia', 'code' => 'TN'],
            ['name' => 'Libya', 'code' => 'LY'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Côte d’Ivoire', 'code' => 'CI'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'CD'],
            ['name' => 'Zimbabwe', 'code' => 'ZW'],
            ['name' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Dominican Republic', 'code' => 'DO'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Puerto Rico', 'code' => 'PR'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Bolivia', 'code' => 'BO'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Suriname', 'code' => 'SR'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Cambodia', 'code' => 'KH'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Mongolia', 'code' => 'MN'],
        ];

        foreach ($nationalities as $nat) {
            Nationality::updateOrCreate(
                ['name' => $nat['name']],
                [
                    'code' => $nat['code'] ?? null,
                    'description' => 'Nationality: ' . $nat['name'],
                    'status_id' => 1,
                    'created_by' => null,
                ]
            );
        }
    }
}